"use strict";

const promisify = require("util.promisify");
const gensync = require("../");

const TEST_ERROR = new Error("TEST_ERROR");

const DID_ERROR = new Error("DID_ERROR");

const doSuccess = gensync({
  sync: () => 42,
  async: () => Promise.resolve(42),
***REMOVED***);

const doError = gensync({
  sync: () => {
    throw DID_ERROR;
  ***REMOVED***,
  async: () => Promise.reject(DID_ERROR),
***REMOVED***);

function throwTestError() {
  throw TEST_ERROR;
***REMOVED***

async function expectResult(
  fn,
  arg,
  { error, value, expectSync = false, syncErrback = expectSync ***REMOVED***
) {
  if (!expectSync) {
    expect(() => fn.sync(arg)).toThrow(TEST_ERROR);
  ***REMOVED*** else if (error) {
    expect(() => fn.sync(arg)).toThrow(error);
  ***REMOVED*** else {
    expect(fn.sync(arg)).toBe(value);
  ***REMOVED***

  if (error) {
    await expect(fn.async(arg)).rejects.toBe(error);
  ***REMOVED*** else {
    await expect(fn.async(arg)).resolves.toBe(value);
  ***REMOVED***

  await new Promise((resolve, reject) => {
    let sync = true;
    fn.errback(arg, (err, val) => {
      try {
        expect(err).toBe(error);
        expect(val).toBe(value);
        expect(sync).toBe(syncErrback);

        resolve();
      ***REMOVED*** catch (e) {
        reject(e);
      ***REMOVED***
    ***REMOVED***);
    sync = false;
  ***REMOVED***);
***REMOVED***

describe("gensync({***REMOVED***)", () => {
  describe("option validation", () => {
    test("disallow async and errback handler together", () => {
      try {
        gensync({
          sync: throwTestError,
          async: throwTestError,
          errback: throwTestError,
        ***REMOVED***);

        throwTestError();
      ***REMOVED*** catch (err) {
        expect(err.message).toMatch(
          /Expected one of either opts.async or opts.errback, but got _both_\./
        );
        expect(err.code).toBe("GENSYNC_OPTIONS_ERROR");
      ***REMOVED***
    ***REMOVED***);

    test("disallow missing sync handler", () => {
      try {
        gensync({
          async: throwTestError,
        ***REMOVED***);

        throwTestError();
      ***REMOVED*** catch (err) {
        expect(err.message).toMatch(/Expected opts.sync to be a function./);
        expect(err.code).toBe("GENSYNC_OPTIONS_ERROR");
      ***REMOVED***
    ***REMOVED***);

    test("errback callback required", () => {
      const fn = gensync({
        sync: throwTestError,
        async: throwTestError,
      ***REMOVED***);

      try {
        fn.errback();

        throwTestError();
      ***REMOVED*** catch (err) {
        expect(err.message).toMatch(/function called without callback/);
        expect(err.code).toBe("GENSYNC_ERRBACK_NO_CALLBACK");
      ***REMOVED***
    ***REMOVED***);
  ***REMOVED***);

  describe("generator function metadata", () => {
    test("automatic naming", () => {
      expect(
        gensync({
          sync: function readFileSync() {***REMOVED***,
          async: () => {***REMOVED***,
        ***REMOVED***).name
      ).toBe("readFile");
      expect(
        gensync({
          sync: function readFile() {***REMOVED***,
          async: () => {***REMOVED***,
        ***REMOVED***).name
      ).toBe("readFile");
      expect(
        gensync({
          sync: function readFileAsync() {***REMOVED***,
          async: () => {***REMOVED***,
        ***REMOVED***).name
      ).toBe("readFileAsync");

      expect(
        gensync({
          sync: () => {***REMOVED***,
          async: function readFileSync() {***REMOVED***,
        ***REMOVED***).name
      ).toBe("readFileSync");
      expect(
        gensync({
          sync: () => {***REMOVED***,
          async: function readFile() {***REMOVED***,
        ***REMOVED***).name
      ).toBe("readFile");
      expect(
        gensync({
          sync: () => {***REMOVED***,
          async: function readFileAsync() {***REMOVED***,
        ***REMOVED***).name
      ).toBe("readFile");

      expect(
        gensync({
          sync: () => {***REMOVED***,
          errback: function readFileSync() {***REMOVED***,
        ***REMOVED***).name
      ).toBe("readFileSync");
      expect(
        gensync({
          sync: () => {***REMOVED***,
          errback: function readFile() {***REMOVED***,
        ***REMOVED***).name
      ).toBe("readFile");
      expect(
        gensync({
          sync: () => {***REMOVED***,
          errback: function readFileAsync() {***REMOVED***,
        ***REMOVED***).name
      ).toBe("readFileAsync");
    ***REMOVED***);

    test("explicit naming", () => {
      expect(
        gensync({
          name: "readFile",
          sync: () => {***REMOVED***,
          async: () => {***REMOVED***,
        ***REMOVED***).name
      ).toBe("readFile");
    ***REMOVED***);

    test("default arity", () => {
      expect(
        gensync({
          sync: function(a, b, c, d, e, f, g) {
            throwTestError();
          ***REMOVED***,
          async: throwTestError,
        ***REMOVED***).length
      ).toBe(7);
    ***REMOVED***);

    test("explicit arity", () => {
      expect(
        gensync({
          arity: 3,
          sync: throwTestError,
          async: throwTestError,
        ***REMOVED***).length
      ).toBe(3);
    ***REMOVED***);
  ***REMOVED***);

  describe("'sync' handler", async () => {
    test("success", async () => {
      const fn = gensync({
        sync: (...args) => JSON.stringify(args),
      ***REMOVED***);

      await expectResult(fn, 42, { value: "[42]", expectSync: true ***REMOVED***);
    ***REMOVED***);

    test("failure", async () => {
      const fn = gensync({
        sync: (...args) => {
          throw JSON.stringify(args);
        ***REMOVED***,
      ***REMOVED***);

      await expectResult(fn, 42, { error: "[42]", expectSync: true ***REMOVED***);
    ***REMOVED***);
  ***REMOVED***);

  describe("'async' handler", async () => {
    test("success", async () => {
      const fn = gensync({
        sync: throwTestError,
        async: (...args) => Promise.resolve(JSON.stringify(args)),
      ***REMOVED***);

      await expectResult(fn, 42, { value: "[42]" ***REMOVED***);
    ***REMOVED***);

    test("failure", async () => {
      const fn = gensync({
        sync: throwTestError,
        async: (...args) => Promise.reject(JSON.stringify(args)),
      ***REMOVED***);

      await expectResult(fn, 42, { error: "[42]" ***REMOVED***);
    ***REMOVED***);
  ***REMOVED***);

  describe("'errback' sync handler", async () => {
    test("success", async () => {
      const fn = gensync({
        sync: throwTestError,
        errback: (...args) => args.pop()(null, JSON.stringify(args)),
      ***REMOVED***);

      await expectResult(fn, 42, { value: "[42]", syncErrback: true ***REMOVED***);
    ***REMOVED***);

    test("failure", async () => {
      const fn = gensync({
        sync: throwTestError,
        errback: (...args) => args.pop()(JSON.stringify(args)),
      ***REMOVED***);

      await expectResult(fn, 42, { error: "[42]", syncErrback: true ***REMOVED***);
    ***REMOVED***);
  ***REMOVED***);

  describe("'errback' async handler", async () => {
    test("success", async () => {
      const fn = gensync({
        sync: throwTestError,
        errback: (...args) =>
          process.nextTick(() => args.pop()(null, JSON.stringify(args))),
      ***REMOVED***);

      await expectResult(fn, 42, { value: "[42]" ***REMOVED***);
    ***REMOVED***);

    test("failure", async () => {
      const fn = gensync({
        sync: throwTestError,
        errback: (...args) =>
          process.nextTick(() => args.pop()(JSON.stringify(args))),
      ***REMOVED***);

      await expectResult(fn, 42, { error: "[42]" ***REMOVED***);
    ***REMOVED***);
  ***REMOVED***);
***REMOVED***);

describe("gensync(function* () {***REMOVED***)", () => {
  test("sync throw before body", async () => {
    const fn = gensync(function*(arg = throwTestError()) {***REMOVED***);

    await expectResult(fn, undefined, {
      error: TEST_ERROR,
      syncErrback: true,
    ***REMOVED***);
  ***REMOVED***);

  test("sync throw inside body", async () => {
    const fn = gensync(function*() {
      throwTestError();
    ***REMOVED***);

    await expectResult(fn, undefined, {
      error: TEST_ERROR,
      syncErrback: true,
    ***REMOVED***);
  ***REMOVED***);

  test("async throw inside body", async () => {
    const fn = gensync(function*() {
      const val = yield* doSuccess();
      throwTestError();
    ***REMOVED***);

    await expectResult(fn, undefined, {
      error: TEST_ERROR,
    ***REMOVED***);
  ***REMOVED***);

  test("error inside body", async () => {
    const fn = gensync(function*() {
      yield* doError();
    ***REMOVED***);

    await expectResult(fn, undefined, {
      error: DID_ERROR,
      expectSync: true,
      syncErrback: false,
    ***REMOVED***);
  ***REMOVED***);

  test("successful return value", async () => {
    const fn = gensync(function*() {
      const value = yield* doSuccess();

      expect(value).toBe(42);

      return 84;
    ***REMOVED***);

    await expectResult(fn, undefined, {
      value: 84,
      expectSync: true,
      syncErrback: false,
    ***REMOVED***);
  ***REMOVED***);

  test("successful final value", async () => {
    const fn = gensync(function*() {
      return 42;
    ***REMOVED***);

    await expectResult(fn, undefined, {
      value: 42,
      expectSync: true,
    ***REMOVED***);
  ***REMOVED***);

  test("yield unexpected object", async () => {
    const fn = gensync(function*() {
      yield {***REMOVED***;
    ***REMOVED***);

    try {
      await fn.async();

      throwTestError();
    ***REMOVED*** catch (err) {
      expect(err.message).toMatch(
        /Got unexpected yielded value in gensync generator/
      );
      expect(err.code).toBe("GENSYNC_EXPECTED_START");
    ***REMOVED***
  ***REMOVED***);

  test("yield suspend yield", async () => {
    const fn = gensync(function*() {
      yield Symbol.for("gensync:v1:start");

      // Should be "yield*" for no error.
      yield {***REMOVED***;
    ***REMOVED***);

    try {
      await fn.async();

      throwTestError();
    ***REMOVED*** catch (err) {
      expect(err.message).toMatch(/Expected GENSYNC_SUSPEND, got {***REMOVED***/);
      expect(err.code).toBe("GENSYNC_EXPECTED_SUSPEND");
    ***REMOVED***
  ***REMOVED***);

  test("yield suspend return", async () => {
    const fn = gensync(function*() {
      yield Symbol.for("gensync:v1:start");

      // Should be "yield*" for no error.
      return {***REMOVED***;
    ***REMOVED***);

    try {
      await fn.async();

      throwTestError();
    ***REMOVED*** catch (err) {
      expect(err.message).toMatch(/Unexpected generator completion/);
      expect(err.code).toBe("GENSYNC_EXPECTED_SUSPEND");
    ***REMOVED***
  ***REMOVED***);
***REMOVED***);

describe("gensync.all()", () => {
  test("success", async () => {
    const fn = gensync(function*() {
      const result = yield* gensync.all([doSuccess(), doSuccess()]);

      expect(result).toEqual([42, 42]);
    ***REMOVED***);

    await expectResult(fn, undefined, {
      value: undefined,
      expectSync: true,
      syncErrback: false,
    ***REMOVED***);
  ***REMOVED***);

  test("error first", async () => {
    const fn = gensync(function*() {
      yield* gensync.all([doError(), doSuccess()]);
    ***REMOVED***);

    await expectResult(fn, undefined, {
      error: DID_ERROR,
      expectSync: true,
      syncErrback: false,
    ***REMOVED***);
  ***REMOVED***);

  test("error last", async () => {
    const fn = gensync(function*() {
      yield* gensync.all([doSuccess(), doError()]);
    ***REMOVED***);

    await expectResult(fn, undefined, {
      error: DID_ERROR,
      expectSync: true,
      syncErrback: false,
    ***REMOVED***);
  ***REMOVED***);

  test("empty list", async () => {
    const fn = gensync(function*() {
      yield* gensync.all([]);
    ***REMOVED***);

    await expectResult(fn, undefined, {
      value: undefined,
      expectSync: true,
      syncErrback: false,
    ***REMOVED***);
  ***REMOVED***);
***REMOVED***);

describe("gensync.race()", () => {
  test("success", async () => {
    const fn = gensync(function*() {
      const result = yield* gensync.race([doSuccess(), doError()]);

      expect(result).toEqual(42);
    ***REMOVED***);

    await expectResult(fn, undefined, {
      value: undefined,
      expectSync: true,
      syncErrback: false,
    ***REMOVED***);
  ***REMOVED***);

  test("error", async () => {
    const fn = gensync(function*() {
      yield* gensync.race([doError(), doSuccess()]);
    ***REMOVED***);

    await expectResult(fn, undefined, {
      error: DID_ERROR,
      expectSync: true,
      syncErrback: false,
    ***REMOVED***);
  ***REMOVED***);
***REMOVED***);
